### ISSUE TITLE
Hello from FastGit

### ISSUE THREAD

**Issue by KevinZonda** [RC1844/FastGithub#1]
Hello, we are @fastgitorg. 

We also provide github mirror <https://hub.fastgit.org>. We support ssh/https clone, release boost, and etc. You can refer to our document -> <https://doc.fastgit.org> and github.com/fastgitorg/document(recommanded).

Are you interested in adding <https://hub.fastgit.org> to your script? 

Have a good day. :)

**Comment by RC1844** [comment]
hi，感谢你提供的信息，我会在测试后进行添加，相信明天就会有结果，但只会是简单的添加，因为我有其他事要忙，忙完后我会进行针对性的修改脚本。
再次感谢

**Comment by KevinZonda** [comment]
> hi，感谢你提供的信息，我会在测试后进行添加，相信明天就会有结果，但只会是简单的添加，因为我有其他事要忙，忙完后我会进行针对性的修改脚本。
> 再次感谢

Thanks a lot

**Comment by RC1844** [comment]
> 非常感谢

简单的修改已推送，这是可用的。
针对性的修改会在后续进行。

**Comment by KevinZonda** [comment]
> > 非常感谢
> 
> 简单的修改已推送，这是可用的。
> 针对性的修改会在后续进行。

👍
