### ISSUE TITLE
https://github.com.cnpmjs.org 已停止解析，并且 hub.fastgit.org 域名更改

### ISSUE THREAD

**Issue by xin053** [RC1844/FastGithub#12]
1. https://github.com.cnpmjs.org 已停止解析
详见下面链接的评论：
https://zhuanlan.zhihu.com/p/465424728

2. hub.fastgit.org 改为 hub.fastgit.xyz
详见
https://doc.fastgit.org/zh-cn/guide.html

**Comment by guoiaoang** [comment]
我之前一直以为是GitHub加强了SSL校验，原来是fastgit改地址了。转到ISSUES页面只有1条，提交完突然变成3条，好巧啊。

**Comment by RC1844** [comment]
抱歉，不知为何没有邮件提醒，所以没能及时回复
后续会移除
