### ISSUE TITLE
插件不能禁用，油猴控制面板设置为禁用后，打开github仍然启用

### ISSUE THREAD

**Issue by lairongxuan** [RC1844/FastGithub#2]
插件不能禁用，油猴控制面板设置为禁用后，打开github仍然启用。何解？

**Comment by RC1844** [comment]
把猴油插件禁用，是chrome插件不是脚本，再看有没有脚本插入，没有就代表你装了多个脚本或者猴油插件出了问题，有则代表你把脚本装在chrome里了，请到chrome://extensions/ 检查
