### ISSUE TITLE
如何自动切换到镜像?

### ISSUE THREAD

**Issue by sisrfeng** [RC1844/FastGithub#7]
有时候别人发来的链接是github的, 想自动切换到fastgit。能否出一个简洁版本, 这剩一个镜像站, 比如fastgit?

感谢大佬！

**Comment by RC1844** [comment]
抱歉，我之前一直没有看见这个问题，你只需要简单的代码就可以完成

location.href="https://hub.fastgit.org"+window.location.pathname

供参考：https://github.com/RC1844/LinkRedirectFix/blob/main/LinkRedirectFix.js
