### ISSUE TITLE
Ioiox已停用，请更换新站

### ISSUE THREAD

**Issue by KB3146706** [RC1844/FastGithub#8]
![Snipaste_2021-06-27_21-34-22](https://user-images.githubusercontent.com/57534077/123546555-a1378e80-d78f-11eb-83a4-4744324d8211.png)
[https://ghproxy.com/](url)

**Comment by KB3146706** [comment]
哦对了，IAPK也失效了，Cloudflare报521错

**Comment by RC1844** [comment]
更新了
